// Movie/Show Categories
export const CATEGORIES = {
  TRENDING: "Trending Now",
  ROMANTIC_ASIAN: "Romantic Asian TV Shows",
  CONTINUE_WATCHING: "Continue Watching for You",
  TOP_TEN_INDIA: "Top 10 Movies in India Today",
  US_COMEDIES: "US TV Comedies",
  NEW_POPULAR: "New & Popular",
  ACTION: "Action Thrillers",
  DOCUMENTARIES: "Documentaries",
  HORROR: "Horror Movies",
  KIDS: "Kids & Family",
  ANIME: "Anime",
  SCI_FI: "Sci-Fi & Fantasy",
  REALITY: "Reality TV",
  CRIME: "Crime TV Shows",
  STAND_UP: "Stand-Up Comedy",
  INTERNATIONAL: "International Movies",
}

// Content Types
export const CONTENT_TYPE = {
  MOVIE: "movie",
  SERIES: "series",
}

// Content Ratings
export const RATINGS = ["TV-MA", "TV-14", "TV-PG", "PG-13", "R", "PG"]

// Genres
export const GENRES = [
  "Action",
  "Adventure",
  "Comedy",
  "Crime",
  "Drama",
  "Fantasy",
  "Horror",
  "Mystery",
  "Romance",
  "Sci-Fi",
  "Thriller",
  "Documentary",
  "Animation",
  "Family",
  "Biography",
  "History",
  "War",
  "Sport",
  "Musical",
  "Western",
]

// Languages
export const LANGUAGES = [
  "English",
  "Hindi",
  "Spanish",
  "French",
  "Korean",
  "Japanese",
  "German",
  "Italian",
  "Portuguese",
  "Russian",
  "Chinese",
  "Arabic",
]

// Sample Content Data
export const CONTENT_DATA = [
  // Trending Now
  {
    id: "t1",
    title: "Stranger Things",
    type: CONTENT_TYPE.SERIES,
    thumbnail: "https://occ-0-4409-3647.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABcElkyM94KkV-6JkAEl5bG0HCdJ9f7eEfQVrbLLZybJIsToWaPi_BCtUciYVN9g2OvedFq2i7OVbTQwtkq75HqWfzLttEcTqhWs.webp?r=d5d",
    year: 2022,
    rating: "TV-14",
    duration: "4 Seasons",
    description:
      "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.",
    genres: ["Sci-Fi", "Horror", "Drama"],
    isNew: false,
    isRecentlyAdded: true,
    category: CATEGORIES.TRENDING,
  },
  {
    id: "t2",
    title: "Money Heist",
    type: CONTENT_TYPE.SERIES,
    thumbnail: "https://occ-0-4409-3647.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABcElkyM94KkV-6JkAEl5bG0HCdJ9f7eEfQVrbLLZybJIsToWaPi_BCtUciYVN9g2OvedFq2i7OVbTQwtkq75HqWfzLttEcTqhWs.webp?r=d5d",
    year: 2021,
    rating: "TV-MA",
    duration: "5 Seasons",
    description:
      "Eight thieves take hostages and lock themselves in the Royal Mint of Spain as a criminal mastermind manipulates the police to carry out his plan.",
    genres: ["Crime", "Drama", "Thriller"],
    isNew: false,
    isRecentlyAdded: false,
    category: CATEGORIES.TRENDING,
  },
  {
    id: "t3",
    title: "The Witcher",
    type: CONTENT_TYPE.SERIES,
    thumbnail: "https://occ-0-4409-3647.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABaXgl7vfD_PLLXddCkR3441soQRWuJHzOkCmqAffBpEnfsHAYwFrDzA3ss4OTkcvZe8t4GsqupOotI7cdLSxR139inIzS-L_y-ZcKReiNNU3cl3LeKttL0AB_-WJLoaOKxWV.jpg?r=878",
    year: 2023,
    rating: "TV-MA",
    duration: "3 Seasons",
    description:
      "Geralt of Rivia, a mutated monster-hunter for hire, journeys toward his destiny in a turbulent world where people often prove more wicked than beasts.",
    genres: ["Fantasy", "Action", "Adventure"],
    isNew: true,
    isRecentlyAdded: true,
    category: CATEGORIES.TRENDING,
  },
  {
    id: "t4",
    title: "Squid Game",
    type: CONTENT_TYPE.SERIES,
    thumbnail: "https://occ-0-4409-3647.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABdzbUU2KNuW4cGYdEOfRsRuTLq5ly1N8qZ5B2KZzsIjtREhMCJvIvNTmW3uDOiWh2ke7hlypCR9k6WSA7_68Bbv61j9_UGT_b9hCrMFFjbD0c7MnYlKbAYbvs2iSc31fLdC8.jpg?r=5f9",
    year: 2021,
    rating: "TV-MA",
    duration: "1 Season",
    description:
      "Hundreds of cash-strapped players accept a strange invitation to compete in children's games. Inside, a tempting prize awaits — with deadly high stakes.",
    genres: ["Drama", "Thriller", "Mystery"],
    isNew: false,
    isRecentlyAdded: false,
    category: CATEGORIES.TRENDING,
  },
  {
    id: "t5",
    title: "Extraction 2",
    type: CONTENT_TYPE.MOVIE,
    thumbnail: "https://occ-0-4409-3647.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABafunU9JTEJKvEcaASsj7Nxoiwijfo1GjvRTLe4NCHWolwr7JkglfM1EioOaa3t6mXVeoYiOFxT5gJQEe_cvP3tt5cOSodDM35YsZ5NsA7buSwS0aIXsSqYoeoQD7r15w0vL.jpg?r=2ec",
    year: 2023,
    rating: "R",
    duration: "2h 3m",
    description:
      "Back from the brink of death, highly skilled commando Tyler Rake takes on another dangerous mission: saving the imprisoned family of a ruthless gangster.",
    genres: ["Action", "Thriller"],
    isNew: false,
    isRecentlyAdded: true,
    category: CATEGORIES.TRENDING,
  },
  {
    id: "t6",
    title: "Wednesday",
    type: CONTENT_TYPE.SERIES,
    thumbnail: "https://occ-0-4409-3647.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABSTf_wnX3UxtQQv4rqHS9REYhUNlVlZ3f26pOGxxvRfJS2fFisYngfvwi6Bdmfy7B-gOOEI4X737lsmC38LRDUA_aRerwtjlqzKsquvDp_JcxhC7myYsu56lny1cWHCV8dEy.jpg?r=7ed",
    year: 2022,
    rating: "TV-14",
    duration: "1 Season",
    description:
      "Smart, sarcastic and a little dead inside, Wednesday Addams investigates a murder spree while making new friends — and foes — at Nevermore Academy.",
    genres: ["Comedy", "Fantasy", "Mystery"],
    isNew: false,
    isRecentlyAdded: false,
    category: CATEGORIES.TRENDING,
  },
  {
    id: "t7",
    title: "The Queen's Gambit",
    type: CONTENT_TYPE.SERIES,
    thumbnail: "https://occ-0-4409-3647.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABRE6yWHz0hw3QMYHKFdMvd6NCt4JGWzYu71ZW3vChDqoD_pnHaR1-nbcnXSEuvsVw3_EZbD5AMAusCOx4pOiGFYdAQAvos2aGDB4pOy7qmWnbezLS5t_J03q-9g4WQndfgaS.jpg?r=0f1",
    year: 2020,
    rating: "TV-MA",
    duration: "1 Season",
    description:
      "In a 1950s orphanage, a young girl reveals an astonishing talent for chess and begins an unlikely journey to stardom while grappling with addiction.",
    genres: ["Drama"],
    isNew: false,
    isRecentlyAdded: false,
    category: CATEGORIES.TRENDING,
  },
  {
    id: "t8",
    title: "Bridgerton",
    type: CONTENT_TYPE.SERIES,
    thumbnail: "https://occ-0-4409-3647.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABXYMhXXEQhdb6SVolS8l3_NVi501UlwW5gzC56BWt4BbD2oR6QSeO5vvCy4SA4dLDh329eZa9mNKZszNyJ1icHmggBHYP8H1BufjN7uQ1g_BPTyIjBjmIYlH-7BZt0jI9Q3O.jpg?r=67e",
    year: 2022,
    rating: "TV-MA",
    duration: "2 Seasons",
    description:
      "The eight close-knit siblings of the Bridgerton family look for love and happiness in London high society.",
    genres: ["Drama", "Romance"],
    isNew: false,
    isRecentlyAdded: true,
    category: CATEGORIES.TRENDING,
  },

  // Romantic Asian TV Shows
  {
    id: "ra1",
    title: "Reply 1988",
    type: CONTENT_TYPE.SERIES,
    thumbnail: "https://occ-0-4409-3647.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABcElkyM94KkV-6JkAEl5bG0HCdJ9f7eEfQVrbLLZybJIsToWaPi_BCtUciYVN9g2OvedFq2i7OVbTQwtkq75HqWfzLttEcTqhWs.webp?r=d5d",
    year: 2015,
    rating: "TV-14",
    duration: "1 Season",
    description:
      "As five families living on the same street in a neighborhood in Seoul in 1988 go through their everyday lives, they soon learn the true meaning of the word 'family'.",
    genres: ["Romance", "Drama", "Comedy"],
    isNew: false,
    isRecentlyAdded: false,
    category: CATEGORIES.ROMANTIC_ASIAN,
  },
  {
    id: "ra2",
    title: "The First Frost",
    type: CONTENT_TYPE.SERIES,
    thumbnail: "https://occ-0-4409-3647.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABQfaPWboxg53bz3KalBBcdb414HlYhnqhsbtg3tfLJTJSZ-AnQVlRmdLTZ9eYAiWNzEjhayQP7XYIxHO2rdPAjih_nq9_vRXSMCFBuWKEvKajHKJ_ONaQa-NNdRqC_TE0fAv.jpg?r=3c7",
    year: 2023,
    rating: "TV-14",
    duration: "1 Season",
    description:
      "A heartwarming romance between two unlikely individuals who find love in the most unexpected circumstances.",
    genres: ["Romance", "Drama"],
    isNew: true,
    isRecentlyAdded: false,
    category: CATEGORIES.ROMANTIC_ASIAN,
  },
  {
    id: "ra3",
    title: "Hometown Cha-Cha-Cha",
    type: CONTENT_TYPE.SERIES,
    thumbnail: "https://occ-0-4409-3647.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABUTiodfmqW03V0IuPKIIRx82J_5cCaMbVfRsRT0Cnsr0wy2z6_KF6Zbq33s69r5ulPboucLae5uL7jNg7E2jfiM2-Q0RoJHhWJ7zf2nlYqSMdTdUvrAfUJpVS0oEs3gA6sxM.jpg?r=0d9",
    year: 2021,
    rating: "TV-14",
    duration: "1 Season",
    description:
      "A big-city dentist opens up a practice in a close-knit seaside village, home to a charming jack-of-all-trades who is her polar opposite in every way.",
    genres: ["Romance", "Comedy", "Drama"],
    isNew: false,
    isRecentlyAdded: false,
    category: CATEGORIES.ROMANTIC_ASIAN,
  },
  {
    id: "ra4",
    title: "My Demon",
    type: CONTENT_TYPE.SERIES,
    thumbnail: "https://occ-0-4409-3647.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABUeSZFN71JIS3g0AdPtzlngl8e_BS1DP6YAhE_GhYZavWqer0V-blNuH3KSoaWkEr3Md-jn3yvQxF_8p5ylFHD7DGyoFk4ryAds.webp?r=545",
    year: 2023,
    rating: "TV-14",
    duration: "1 Season",
    description:
      "A cold-hearted heiress and a powerful demon make a dangerous contract: she'll help him recover his powers if he protects her from those who want her dead.",
    genres: ["Romance", "Fantasy", "Comedy"],
    isNew: false,
    isRecentlyAdded: false,
    category: CATEGORIES.ROMANTIC_ASIAN,
  },
  {
    id: "ra5",
    title: "Business Proposal",
    type: CONTENT_TYPE.SERIES,
    thumbnail: "https://occ-0-4409-3647.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABRVm3K1ZR_-hTxP1_pEN4-dt_nJ-3VoaMVYsy5Q7J_7CS4bPKnV_AboaD1VbquUh_yoJK_JPSahXW6ihZEGNDe7txsnVpexdb5j5xjZYKiGqAli_Z5ugY5kBwHHfM6AZMFdU.jpg?r=6d5",
    year: 2022,
    rating: "TV-14",
    duration: "1 Season",
    description:
      "In disguise as her friend, Ha-ri shows up to a blind date to scare him away. But plans go awry when he turns out to be her CEO — and makes a proposal.",
    genres: ["Romance", "Comedy"],
    isNew: false,
    isRecentlyAdded: false,
    category: CATEGORIES.ROMANTIC_ASIAN,
  },
  {
    id: "ra6",
    title: "Falling Into Your Smile",
    type: CONTENT_TYPE.SERIES,
    thumbnail: "https://occ-0-4409-3647.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABdkDi3DrQb5A3aUAzTjiTzCZUAs1jrBLARqDfl8_4H0NeqP-yu80AKt1v0Bz8oopRbDHvlCU3tk73Ow5xxa41S8jHEYj-PiCSSY.webp?r=a6e",
    year: 2021,
    rating: "TV-14",
    duration: "1 Season",
    description:
      "When a professional gamer is injured, a talented rookie becomes the first female player in a top e-sports team, and romance blooms.",
    genres: ["Romance", "Drama", "Sports"],
    isNew: false,
    isRecentlyAdded: false,
    category: CATEGORIES.ROMANTIC_ASIAN,
  },
  {
    id: "ra7",
    title: "Crash Landing on You",
    type: CONTENT_TYPE.SERIES,
    thumbnail: "https://occ-0-4409-3647.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABd_DmKWg4SKlwTBTMjWwXl2kfSXyklfw84zuxv7XF1YgiBxa1JjAFJXAnrnOlTi4wGE5nr2TLF8RtalKJH5oHI7IUMt9ajiSA8g.webp?r=8bb",
    year: 2020,
    rating: "TV-14",
    duration: "1 Season",
    description:
      "A paragliding mishap drops a South Korean heiress in North Korea — and into the life of an army officer, who decides he will help her hide.",
    genres: ["Romance", "Drama", "Comedy"],
    isNew: false,
    isRecentlyAdded: false,
    category: CATEGORIES.ROMANTIC_ASIAN,
  },
  {
    id: "ra8",
    title: "It's Okay to Not Be Okay",
    type: CONTENT_TYPE.SERIES,
    thumbnail: "https://occ-0-4409-3647.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABemRAkbhnqLiLVPbj3k15EyU8moM2FT9ww9kg-cbnuXBZkzekFmtL7NvBvtJihoOQsAivCKUTXjUcRtmvrARbjZILnptEfMHKxc.webp?r=ff6",
    year: 2020,
    rating: "TV-14",
    duration: "1 Season",
    description:
      "An extraordinary road to emotional healing opens up for an antisocial children's book writer and a selfless psych ward caretaker when they cross paths.",
    genres: ["Romance", "Drama"],
    isNew: false,
    isRecentlyAdded: false,
    category: CATEGORIES.ROMANTIC_ASIAN,
  },

  // Continue Watching
  {
    id: "cw1",
    title: "Brooklyn Nine-Nine",
    type: CONTENT_TYPE.SERIES,
    thumbnail: "https://occ-0-4409-3647.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABSFjCc1l7lZGXt2FXPsFmWUVoRZaF70XSsjrAW1pSeLYrBL3-txY6ESvmRnk7cN2YPCwl1bJJrWHKzNKEMMv4VkV2zvmaLBPdkc.webp?r=f0a",
    year: 2019,
    rating: "TV-14",
    duration: "8 Seasons",
    description:
      "Jake Peralta, an immature, but talented detective in Brooklyn's 99th Precinct, comes into conflict with his new commanding officer, the serious and stern Captain Raymond Holt.",
    genres: ["Comedy", "Crime"],
    isNew: false,
    isRecentlyAdded: false,
    progress: 70,
    category: CATEGORIES.CONTINUE_WATCHING,
  },
  {
    id: "cw2",
    title: "When Life Gives You Tangerines",
    type: CONTENT_TYPE.SERIES,
    thumbnail: "https://occ-0-4409-3647.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABaoPmbOQFzjADveLiof8LcyIzBy8iSRDrsYBaDBZGVDdc7ddluewMNoYbTPF_Trg2INA5FRPmCT9mf4-jFXJpJtoTExpEmNqgfo.webp?r=4a8",
    year: 2023,
    rating: "TV-14",
    duration: "1 Season",
    description:
      "A heartwarming story about finding joy in the little things and making the most of what life gives you.",
    genres: ["Drama", "Comedy"],
    isNew: true,
    isRecentlyAdded: false,
    progress: 30,
    category: CATEGORIES.CONTINUE_WATCHING,
  },
  {
    id: "cw3",
    title: "Meenakshi Sundareshwar",
    type: CONTENT_TYPE.MOVIE,
    thumbnail: "https://occ-0-4409-3647.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABaZ9sIbmEmM1R1IU6dKFhpuF8Ll70H8JpkJ1aFMm6wwEh-NxjhyfNrBVI9yglv9TP2BAYd5nqF2inSiHEhC8bBkw2agcHYLZ3lcH0Emzw74pPHZz3-pZ8IdEIIaeHFmTvyTIFJLZl79QqzLlrHmV3fcs9LwieKeYlsxj5shDJg.webp?r=9c5",
    year: 2021,
    rating: "TV-14",
    duration: "2h 21m",
    description:
      "Forced to live apart due to a unique job prospect, newlyweds Meenakshi and Sundareshwar try to build a long-distance relationship.",
    genres: ["Romance", "Comedy"],
    isNew: false,
    isRecentlyAdded: false,
    progress: 45,
    category: CATEGORIES.CONTINUE_WATCHING,
  },
  {
    id: "cw4",
    title: "Suits",
    type: CONTENT_TYPE.SERIES,
    thumbnail: "https://occ-0-4409-3647.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABY27nQcjbnE6sUnC6Oqst3GUfQxPYT5EqlE11DQGqA6bR0groz5eguQa9f1GVWRuWYNyXL0bnoHqAZ1lbr-qc16-9MpKiZNnD68.webp?r=e72",
    year: 2019,
    rating: "TV-14",
    duration: "9 Seasons",
    description:
      "On the run from a drug deal gone bad, brilliant college dropout Mike Ross finds himself working with Harvey Specter, one of New York City's best lawyers.",
    genres: ["Drama", "Comedy"],
    isNew: false,
    isRecentlyAdded: false,
    progress: 90,
    category: CATEGORIES.CONTINUE_WATCHING,
  },
  {
    id: "cw5",
    title: "Khakee",
    type: CONTENT_TYPE.SERIES,
    thumbnail: "https://occ-0-4409-3647.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABevI6-1mku45--hhsUnl2Abs-XibZMfAHCIc4rtBB55tzyS7ddQLY1JX_XQzU3ScWr_xqMqi1LZRINYAq3SbTOUiuxU74lS8kUU.webp?r=f91",
    year: 2022,
    rating: "TV-MA",
    duration: "1 Season",
    description:
      "As a righteous cop pursues a merciless criminal in Bihar, he finds himself navigating a deadly chase and a moral battle with a system that expects different things from him.",
    genres: ["Crime", "Drama", "Action"],
    isNew: false,
    isRecentlyAdded: true,
    progress: 20,
    category: CATEGORIES.CONTINUE_WATCHING,
  },
  {
    id: "cw6",
    title: "Karma",
    type: CONTENT_TYPE.MOVIE,
    thumbnail: "https://occ-0-4409-3647.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABdXQ6zIcTamlrXVQNNmh0uk6qZL7ZJEcZN39tEavsDM1tePha9wecQ_ESsfeQ3whe9ypoDzTJ09152ASHl0Gr0r_DWqJdxLtGv9qbreTpDIPISk2bC_7qvtBA1_HfT6xbZ9tvL_TRbAxYcGx-1TEaHUDcSKGKYMfUxMf6kbYh3aMboNF_fZ7ZVZP-yqq5adc-OC84jhwAdys6w0r_ZAhUgB32x__9qWeVM_XaOM.webp?r=300",
    year: 2023,
    rating: "TV-MA",
    duration: "2h 15m",
    description: "A thrilling tale of destiny and consequences, where past actions come back to haunt the present.",
    genres: ["Thriller", "Drama"],
    isNew: false,
    isRecentlyAdded: true,
    progress: 10,
    category: CATEGORIES.CONTINUE_WATCHING,
  },

  // Top 10 Movies in India
  {
    id: "top1",
    title: "Test",
    type: CONTENT_TYPE.MOVIE,
    thumbnail: "https://occ-0-4409-3647.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABU8QVv1RWauN7Lc0C2aBjra6d--o3ll-JKHMdbtJ4M_kraDa4n2EujxA9e0Uzs1uaqOr-RBFAOgZ7mhoSq2XYTIELFp3FDyfsZQ.webp?r=ba8",
    year: 2023,
    rating: "TV-MA",
    duration: "2h 30m",
    description:
      "A gripping drama about a cricket player's journey through the challenges of professional sports and personal life.",
    genres: ["Drama", "Sports"],
    isNew: false,
    isRecentlyAdded: true,
    rank: 1,
    category: CATEGORIES.TOP_TEN_INDIA,
  },
  {
    id: "top2",
    title: "Animal",
    type: CONTENT_TYPE.MOVIE,
    thumbnail: "https://occ-0-4409-3647.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABcLIFreBhoJFYtDxCv4d2UF3Ws0MkES8unfOhiCVZe1x2lKSsRpLaTkWeBL_v8tzonZOdp_djoqorMh2yvHKjYUidJvFTvEXPKNTH2zABQ15-zEAUv3R_A1NZQF4ETGTCW08Hp_xohNV0_qLAZAuL9eb_k6RRU-Byw7UEm_kef2js7CGJl4zf2JR7sppLWv6XkCrlJ7B2E3P7eu-YkBmnrtL3bLWBtf8mbtTSvA.webp?r=171",
    year: 2023,
    rating: "TV-MA",
    duration: "3h 21m",
    description: "A son undergoes a remarkable transformation as a result of his unconditional love for his father.",
    genres: ["Action", "Crime", "Drama"],
    isNew: false,
    isRecentlyAdded: true,
    rank: 2,
    category: CATEGORIES.TOP_TEN_INDIA,
  },
  {
    id: "top3",
    title: "Kraven the Hunter",
    type: CONTENT_TYPE.MOVIE,
    thumbnail: "https://occ-0-4409-3647.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABcElkyM94KkV-6JkAEl5bG0HCdJ9f7eEfQVrbLLZybJIsToWaPi_BCtUciYVN9g2OvedFq2i7OVbTQwtkq75HqWfzLttEcTqhWs.webp?r=d5d",
    year: 2023,
    rating: "PG-13",
    duration: "1h 54m",
    description:
      "Russian immigrant Sergei Kravinoff is on a mission to prove that he is the greatest hunter in the world.",
    genres: ["Action", "Adventure", "Thriller"],
    isNew: false,
    isRecentlyAdded: true,
    rank: 3,
    category: CATEGORIES.TOP_TEN_INDIA,
  },
  {
    id: "top4",
    title: "Dragon",
    type: CONTENT_TYPE.MOVIE,
    thumbnail: "https://occ-0-4409-3647.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABXYMhXXEQhdb6SVolS8l3_NVi501UlwW5gzC56BWt4BbD2oR6QSeO5vvCy4SA4dLDh329eZa9mNKZszNyJ1icHmggBHYP8H1BufjN7uQ1g_BPTyIjBjmIYlH-7BZt0jI9Q3O.jpg?r=67e",
    year: 2023,
    rating: "PG",
    duration: "1h 42m",
    description: "An animated adventure about a young boy who befriends a dragon and embarks on an epic journey.",
    genres: ["Animation", "Adventure", "Family"],
    isNew: false,
    isRecentlyAdded: true,
    rank: 4,
    category: CATEGORIES.TOP_TEN_INDIA,
  },
  {
    id: "top5",
    title: "Officer",
    type: CONTENT_TYPE.MOVIE,
    thumbnail: "https://occ-0-4409-3647.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABdDK81kq-XAsjF_ZUC8yfFSeefXD-9mL0h3j9sGZT7u9C1FOLF2fn6nqaORjiLXRw_3-9yAf1g5h82E7BGjGqjuc8X_f_Cz_95g.webp?r=1a7",
    year: 2023,
    rating: "TV-MA",
    duration: "2h 12m",
    description:
      "A dedicated police officer goes beyond the call of duty to solve a complex case that threatens the city's safety.",
    genres: ["Crime", "Thriller", "Action"],
    isNew: false,
    isRecentlyAdded: true,
    rank: 5,
    category: CATEGORIES.TOP_TEN_INDIA,
  },
  {
    id: "top6",
    title: "The Life List",
    type: CONTENT_TYPE.MOVIE,
    thumbnail: "https://occ-0-4409-3647.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABUITJV66q8-YnlHqdKZxMEXFx9b5sKBtxqBXRy00LAyvA6VX3X0G_9FywtpiPgU31iMkSJ69IDGEujZDaH7guWcMxc7N2K53pGM.webp?r=1a5",
    year: 2023,
    rating: "TV-14",
    duration: "1h 58m",
    description:
      "A woman discovers her late mother's bucket list and decides to complete all the adventures, finding love and herself along the way.",
    genres: ["Romance", "Drama", "Comedy"],
    isNew: false,
    isRecentlyAdded: true,
    rank: 6,
    category: CATEGORIES.TOP_TEN_INDIA,
  },
  {
    id: "top7",
    title: "Jawan",
    type: CONTENT_TYPE.MOVIE,
    thumbnail: "https://occ-0-4409-3647.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABegBbtClFMXQnt1Oy1jeg80XpACW-reeA6RAeDgZrdgJOCV8QgQRXhz8zFG0rAg84gg-JgRxXTe25XxCFVHl7h09Nk3lfDAk5ks.webp?r=306",
    year: 2023,
    rating: "TV-14",
    duration: "2h 45m",
    description:
      "A man is driven by a personal vendetta to rectify the wrongs in society, while keeping a promise made years ago.",
    genres: ["Action", "Thriller"],
    isNew: false,
    isRecentlyAdded: true,
    rank: 7,
    category: CATEGORIES.TOP_TEN_INDIA,
  },
  {
    id: "top8",
    title: "Pathaan",
    type: CONTENT_TYPE.MOVIE,
    thumbnail: "https://occ-0-4409-3647.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABfccI4TPOHYecdtnbpQjNFI4Y8U0NGvdWBkMgNguOlRc1irJo4dKx8bwQ9W7ObfvOHij5yVfxZh4kAR5275qeHGDpHfSpn4Xhoc.webp?r=745",
    year: 2023,
    rating: "TV-14",
    duration: "2h 26m",
    description:
      "An Indian spy takes on the leader of a group of mercenaries who have nefarious plans to target his homeland.",
    genres: ["Action", "Adventure", "Thriller"],
    isNew: false,
    isRecentlyAdded: true,
    rank: 8,
    category: CATEGORIES.TOP_TEN_INDIA,
  },
  {
    id: "top9",
    title: "Dunki",
    type: CONTENT_TYPE.MOVIE,
    thumbnail: "https://occ-0-4409-3647.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABQ43t4stBxSGLBj5EHk4K7IUay7n7_jbEfiPoH9_TV9lrDZQ9Mm4BlqB-yzfJVQGm0n2ZI8rMYq5qhOuZpc6w3_4oVkf2hu3DCc.webp?r=7dc",
    year: 2023,
    rating: "TV-14",
    duration: "2h 41m",
    description: "Four friends from a village in Punjab dream of going to England in search of a better life.",
    genres: ["Comedy", "Drama"],
    isNew: true,
    isRecentlyAdded: true,
    rank: 9,
    category: CATEGORIES.TOP_TEN_INDIA,
  },
  {
    id: "top10",
    title: "Tiger 3",
    type: CONTENT_TYPE.MOVIE,
    thumbnail: "https://occ-0-4409-3647.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABU6n_QPdyRrNMTj900PUasROeodMewrcRqJvruAh6F09rcRCue8Foavg8LhtPRDhRT2ji_IMdgqaVuB1iVqyfG8XJNb6lkvOuvg.webp?r=8d6",
    year: 2023,
    rating: "TV-14",
    duration: "2h 35m",
    description: "Tiger races against time to save both his family and country from a terrorist organization.",
    genres: ["Action", "Thriller"],
    isNew: true,
    isRecentlyAdded: true,
    rank: 10,
    category: CATEGORIES.TOP_TEN_INDIA,
  },

  // Action Thrillers
  {
    id: "act1",
    title: "Extraction",
    type: CONTENT_TYPE.MOVIE,
    thumbnail: "https://occ-0-4409-3647.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABaoPmbOQFzjADveLiof8LcyIzBy8iSRDrsYBaDBZGVDdc7ddluewMNoYbTPF_Trg2INA5FRPmCT9mf4-jFXJpJtoTExpEmNqgfo.webp?r=4a8",
    year: 2020,
    rating: "R",
    duration: "1h 56m",
    description:
      "A hardened mercenary's mission becomes a soul-searching race to survive when he's sent into Bangladesh to rescue a drug lord's kidnapped son.",
    genres: ["Action", "Thriller"],
    isNew: false,
    isRecentlyAdded: false,
    category: CATEGORIES.ACTION,
  },
  {
    id: "act2",
    title: "The Gray Man",
    type: CONTENT_TYPE.MOVIE,
    thumbnail: "https://occ-0-4409-3647.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABVOEXOmy5iOuKOf71zAuvgqc4A9zQZoMsr0Tr4Z7t1RnaBMMgNxANiJK3xDwenaRAOkwfazFurtwARhvag06W6CoSYDi030z62A.webp?r=81c",
    year: 2022,
    rating: "PG-13",
    duration: "2h 9m",
    description:
      "When a shadowy CIA agent uncovers damning agency secrets, he's hunted across the globe by a sociopathic rogue operative who's put a bounty on his head.",
    genres: ["Action", "Thriller"],
    isNew: false,
    isRecentlyAdded: false,
    category: CATEGORIES.ACTION,
  },
  {
    id: "act3",
    title: "Red Notice",
    type: CONTENT_TYPE.MOVIE,
    thumbnail: "https://occ-0-4409-3647.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABbnAAdTXpIY-P7Rn7dteWmoLQ5KOmrCBHHV0MNHzihyYr8lNje9bY-xrsxL1NvR7HZQZA2aaStZnuSgtPc08-217m1WRS-zCXEY.webp?r=3bf",
    year: 2021,
    rating: "PG-13",
    duration: "1h 58m",
    description:
      "An FBI profiler pursuing the world's most wanted art thief becomes his reluctant partner in crime to catch an elusive crook who's always one step ahead.",
    genres: ["Action", "Comedy", "Thriller"],
    isNew: false,
    isRecentlyAdded: false,
    category: CATEGORIES.ACTION,
  },
  {
    id: "act4",
    title: "6 Underground",
    type: CONTENT_TYPE.MOVIE,
    thumbnail: "https://occ-0-4409-3647.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABcWcqZBQjx3OLuigahkZ_tt4lq2WCIC1q7lw0pEwGImfDTN8BmP84DRn9o8mFVxlSuu7WdDUzZp8huPLigolt469qcgsV_3t7Ds.webp?r=c57",
    year: 2019,
    rating: "R",
    duration: "2h 8m",
    description:
      "After faking his death, a tech billionaire recruits a team of international operatives for a bold and bloody mission to take down a brutal dictator.",
    genres: ["Action", "Thriller"],
    isNew: false,
    isRecentlyAdded: false,
    category: CATEGORIES.ACTION,
  },
  {
    id: "act5",
    title: "The Old Guard",
    type: CONTENT_TYPE.MOVIE,
    thumbnail: "https://occ-0-4409-3647.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABXgY1fZMzg90WXTOIUGboO1RkCRqenOVHACb3r4O0GhewM7zWlfVGFmu9CeG1JmVoM8-wouvadejvn88EE1Y6uTeYGC2mmz2CiA.webp?r=1bd",
    year: 2020,
    rating: "R",
    duration: "2h 5m",
    description:
      "Four undying warriors who've secretly protected humanity for centuries become targeted for their mysterious powers just as they discover a new immortal.",
    genres: ["Action", "Fantasy"],
    isNew: false,
    isRecentlyAdded: false,
    category: CATEGORIES.ACTION,
  },
  {
    id: "act6",
    title: "Triple Frontier",
    type: CONTENT_TYPE.MOVIE,
    thumbnail: "https://occ-0-4409-3647.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABUW7-5TWv4bTk_B3QtnOSknIoLVV6E9B9esjI0FGqxlyrdI2amTsUBsS-fDx4OiHL7DdOsxIdOdQuvCHGi-Q2LJS3K-YN3Ayie0.webp?r=59e",
    year: 2019,
    rating: "R",
    duration: "2h 5m",
    description:
      "Loyalties are tested when five former special forces operatives reunite to steal a drug lord's fortune, unleashing a chain of unintended consequences.",
    genres: ["Action", "Adventure", "Crime"],
    isNew: false,
    isRecentlyAdded: false,
    category: CATEGORIES.ACTION,
  },

  // Horror Movies
  {
    id: "hor1",
    title: "Bird Box",
    type: CONTENT_TYPE.MOVIE,
    thumbnail: "https://occ-0-4409-3647.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABSYIh5rVV46qywjZNSMy-6iEQuiNKUWcf5zhfuxQ6HNalmfM1HQVzUtkt1L7RPp1DDIKehxP2q1pZUthKu0HKo3uyZBZtFn08XE.webp?r=0a1",
    year: 2018,
    rating: "R",
    duration: "2h 4m",
    description:
      "Five years after an ominous unseen presence drives most of society to suicide, a survivor and her two children make a desperate bid to reach safety.",
    genres: ["Horror", "Sci-Fi", "Thriller"],
    isNew: false,
    isRecentlyAdded: false,
    category: CATEGORIES.HORROR,
  },
  {
    id: "hor2",
    title: "The Ritual",
    type: CONTENT_TYPE.MOVIE,
    thumbnail: "https://occ-0-4409-3647.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABZy-tUHxFDfWHe67NHZMwxz1qT8vXII294rj6oKwBOE2FGaKV6r4pidzbJX17bZlBpPYysWQFSK0BtFcOJDtMab0RaIrbWfocWA.webp?r=121",
    year: 2017,
    rating: "TV-MA",
    duration: "1h 34m",
    description:
      "Four friends with a long-standing — but strained — connection take a hiking trip into the Swedish wilderness, from which they may never return.",
    genres: ["Horror", "Mystery", "Thriller"],
    isNew: false,
    isRecentlyAdded: false,
    category: CATEGORIES.HORROR,
  },
  {
    id: "hor3",
    title: "The Platform",
    type: CONTENT_TYPE.MOVIE,
    thumbnail: "https://occ-0-4409-3647.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABcIqpxt78aGQebWsgi6xl3QxHvln3wAKCqcxlgb0GuloWwR_wLE7vGFbSRJilt58YtbigbjyY9fuQ2CHdLISVRpkEQ13P_kV2zg.webp?r=d28",
    year: 2019,
    rating: "TV-MA",
    duration: "1h 34m",
    description:
      "A slab of food descends floor by floor in a prison. The inmates above eat heartily, leaving those below starving and desperate. A rebellion is imminent.",
    genres: ["Horror", "Sci-Fi", "Thriller"],
    isNew: false,
    isRecentlyAdded: false,
    category: CATEGORIES.HORROR,
  },
  {
    id: "hor4",
    title: "Veronica",
    type: CONTENT_TYPE.MOVIE,
    thumbnail: "https://occ-0-4409-3647.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABTEoPpsT70PFegANMJvK3H8ORfZPZOBfZRHZXs47lrawG-ZyAIssuroZJ7-AZE-hDY-dKXrUhxa57yQQDj9a6QTk5bM8Ifl5_ek.webp?r=934",
    year: 2017,
    rating: "TV-MA",
    duration: "1h 45m",
    description:
      "In 1991 Madrid, after holding a séance at school, a teen girl minding her younger siblings at home suspects an evil force has entered their apartment.",
    genres: ["Horror", "Drama"],
    isNew: false,
    isRecentlyAdded: false,
    category: CATEGORIES.HORROR,
  },
  {
    id: "hor5",
    title: "His House",
    type: CONTENT_TYPE.MOVIE,
    thumbnail: "https://occ-0-4409-3647.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABUITJV66q8-YnlHqdKZxMEXFx9b5sKBtxqBXRy00LAyvA6VX3X0G_9FywtpiPgU31iMkSJ69IDGEujZDaH7guWcMxc7N2K53pGM.webp?r=1a5",
    year: 2020,
    rating: "TV-14",
    duration: "1h 33m",
    description:
      "As a young refugee couple tries to start over in England, they're tormented by a sinister force tied to the horrors they escaped in war-torn South Sudan.",
    genres: ["Horror", "Drama", "Thriller"],
    isNew: false,
    isRecentlyAdded: false,
    category: CATEGORIES.HORROR,
  },

  // Kids & Family
  {
    id: "kid1",
    title: "The Mitchells vs. the Machines",
    type: CONTENT_TYPE.MOVIE,
    thumbnail: "https://occ-0-4409-3647.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABUQJlU88X-HsKAMp9Y0FjR-hObf8O-Q4YyT1DtnSYRCMfduN4cAwglH4QA1IntuRb1Cj1vtJpmxRgRMzoM3X3lG9BeSULiEtJVw.webp?r=f21",
    year: 2021,
    rating: "PG",
    duration: "1h 53m",
    description:
      "A quirky, dysfunctional family's road trip is upended when they find themselves in the middle of the robot apocalypse and suddenly become humanity's unlikeliest last hope.",
    genres: ["Animation", "Adventure", "Comedy"],
    isNew: false,
    isRecentlyAdded: false,
    category: CATEGORIES.KIDS,
  },
  {
    id: "kid2",
    title: "Klaus",
    type: CONTENT_TYPE.MOVIE,
    thumbnail: "https://occ-0-4409-3647.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABYzcgGooOYR9njrMMgJyiXk6_gCvtb1lz0PQsdwCcq5hBCZn9mJGBkVfXK8NEWsrrk2KXeeIQTjG_X_YxUWp_ZHlpHxkB1GEA9s.webp?r=26d",
    year: 2019,
    rating: "PG",
    duration: "1h 38m",
    description:
      "A selfish postman and a reclusive toymaker form an unlikely friendship, delivering joy to a cold, dark town that desperately needs it.",
    genres: ["Animation", "Adventure", "Comedy"],
    isNew: false,
    isRecentlyAdded: false,
    category: CATEGORIES.KIDS,
  },
  {
    id: "kid3",
    title: "Over the Moon",
    type: CONTENT_TYPE.MOVIE,
    thumbnail: "https://occ-0-4409-3647.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABYq0p4UZkBhKJBV24cPpMGR6p87x6fWs2vjy5c_RhJk4TZUwvN46nKsyyUu9sr7-fVmMLZC_hagj0NArIKcDbyJmvQg422z85Mg.webp?r=6d8",
    year: 2020,
    rating: "PG",
    duration: "1h 40m",
    description:
      "Fueled by memories of her mother, resourceful Fei Fei builds a rocket to the moon on a mission to prove the existence of a legendary moon goddess.",
    genres: ["Animation", "Adventure", "Family"],
    isNew: false,
    isRecentlyAdded: false,
    category: CATEGORIES.KIDS,
  },
  {
    id: "kid4",
    title: "The Willoughbys",
    type: CONTENT_TYPE.MOVIE,
    thumbnail: "https://occ-0-4409-3647.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABVuFQLqw1an6CvUx--IfhAVvTpTjzSa2cac9RdZimtRDlvQNq3JdISjSTywwao_du0TQe12alsiG2ahGxueOqVqgRIoF6Hi60Ig.webp?r=31d",
    year: 2020,
    rating: "PG",
    duration: "1h 30m",
    description:
      "Four siblings with horribly selfish parents hatch a plan to get rid of them for good and form a perfectly imperfect family of their own.",
    genres: ["Animation", "Adventure", "Comedy"],
    isNew: false,
    isRecentlyAdded: false,
    category: CATEGORIES.KIDS,
  },
  {
    id: "kid5",
    title: "The Sea Beast",
    type: CONTENT_TYPE.MOVIE,
    thumbnail: "https://occ-0-4409-3647.1.nflxso.net/dnm/api/v6/Qs00mKCpRvrkl3HZAN5KwEL1kpE/AAAABd_zWUXc2sAuWFF318MjyL6PWTCxmuJKCUESGLIxVN7clPAsECA9nu69hQc6Fp-buKZqlhZMoZWS79_-Ral7C6wzhUECpaR3IFE.webp?r=12d",
    year: 2022,
    rating: "PG",
    duration: "1h 59m",
    description:
      "A legendary sea monster hunter's life is turned upside down when a young girl stows away on his ship and befriends the most dangerous beast of them all.",
    genres: ["Animation", "Adventure", "Family"],
    isNew: false,
    isRecentlyAdded: true,
    category: CATEGORIES.KIDS,
  },
]

// Get content by category
export const getContentByCategory = (category: string) => {
  return CONTENT_DATA.filter((item) => item.category === category)
}

// Get content by type (movie or series)
export const getContentByType = (type: string) => {
  return CONTENT_DATA.filter((item) => item.type === type)
}

// Get all categories with content
export const getAllCategories = () => {
  const categories = Object.values(CATEGORIES)
  return categories.filter((category) => CONTENT_DATA.some((item) => item.category === category))
}

// Get trending content for homepage
export const getTrendingContent = () => {
  return CONTENT_DATA.filter(
    (item) => item.category === CATEGORIES.TRENDING || item.isNew || item.isRecentlyAdded,
  ).slice(0, 12)
}

// Get content by ID
export const getContentById = (id: string) => {
  return CONTENT_DATA.find((item) => item.id === id)
}

